module SpirV.BuiltIn (BuiltIn(..)) where
data BuiltIn
  = Position 
  | PointSize 
  | ClipVertex 
  | ClipDistance 
  | CullDistance 
  | VertexId 
  | InstanceId 
  | PrimitiveId 
  | InvocationId 
  | Layer 
  | ViewportIndex 
  | TessLevelOuter 
  | TessLevelInner 
  | TessCoord 
  | PatchVertices 
  | FragCoord 
  | PointCoord 
  | FrontFacing 
  | SampleId 
  | SamplePosition 
  | SampleMask 
  | FragColor 
  | FragDepth 
  | HelperInvocation 
  | NumWorkgroups 
  | WorkgroupSize 
  | WorkgroupId 
  | LocalInvocationId 
  | GlobalInvocationId 
  | LocalInvocationIndex 
  | WorkDim 
  | GlobalSize 
  | EnqueuedWorkgroupSize 
  | GlobalOffset 
  | GlobalLinearId 
  | WorkgroupLinearId 
  | SubgroupSize 
  | SubgroupMaxSize 
  | NumSubgroups 
  | NumEnqueuedSubgroups 
  | SubgroupId 
  | SubgroupLocalInvocationId 