module SpirV.Decoration (Decoration(..)) where
data Decoration
  = PrecisionLow 
  | PrecisionMedium 
  | PrecisionHigh 
  | Block 
  | BufferBlock 
  | RowMajor 
  | ColMajor 
  | GLSLShared 
  | GLSLStd140 
  | GLSLStd430 
  | GLSLPacked 
  | Smooth 
  | Noperspective 
  | Flat 
  | Patch 
  | Centroid 
  | Sample 
  | Invariant 
  | Restrict 
  | Aliased 
  | Volatile 
  | Constant 
  | Coherent 
  | Nonwritable 
  | Nonreadable 
  | Uniform 
  | NoStaticUse 
  | CPacked 
  | FPSaturatedConversion 
  | Stream 
  | Location 
  | Component 
  | Index 
  | Binding 
  | DescriptorSet 
  | Offset 
  | Alignment 
  | XfbBuffer 
  | Stride 
  | BuiltIn 
  | FuncParamAttr 
  | FPRoundingMode 
  | FPFastMathMode 
  | LinkageType 
  | SpecId 